# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
# source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
#use_frameworks!
use_frameworks! :linkage => :static
inhibit_all_warnings!

target 'YAMAlbumAdressParserDemo' do

  pod 'Alamofire', '~> 5.4'	

end
